/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import aoc.day1.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val day6 = Day6();

    day6.result(false)
}
