/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import aoc.day1.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val day7 = Day7();

    day7.result(true)

}
