/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import aoc.day1.Day2
import aoc.day1.Day3
import aoc.day1.Day4
import aoc.day1.Day5

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val day5 = Day5();

    println(day5.result())
}
